services:
    postgres-db:
        image: postgres:18
        container_name: mi-postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password123
            POSTGRES_DB: marketing_intelligence
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql
    rabbitmq:
        image: rabbitmq:3-management
        container_name: mi-rabbitmq
        ports:
          - "5672:5672"
          - "15672:15672"
        environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
    redis:
        image: redis:7-alpine
        container_name: mi-redis
        ports:
          - "6379:6379"
        volumes:
          - redis_data:/data
        command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_data:
  redis_data: